apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cm
  namespace: postgres
data:
  postgres_db: postgresdb
  postgres_user: admin
  pg_hba.conf: |
    local   all             all                                    trust
    host    all             all             all                    scram-sha-256
    host    replication     all             all                    scram-sha-256
