apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/cm.yaml
  - manifests/secret.yaml
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml
  - manifests/cronjob.yaml
images:
  - name: CUTLASS_APP_IMAGE
    newName: europe-north1-docker.pkg.dev/my-project/cutlass-app
    newTag: placeholder

