apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-deployment
  template:
    metadata:
      name: backup-deployment
      labels:
        app: backup-deployment
    spec:
      containers:
        - name: backup-deployment
          image: europe-north1-docker.pkg.dev/dwk-gke-484109/cutlass-backup/cutlass-backup:backup-04b27166427994322cdcc612cfb088e5c0d8298f
          imagePullPolicy: IfNotPresent
          env:
            - name: URL
              value: "postgres://dwkmntair:verysecret@postgres-svc.postgres:5432/cutlass"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cutlass-secret
                  key: db_password
            - name: SIGNED_UPLOAD_URL
              valueFrom:
                configMapKeyRef:
                  name: backup-cm
                  key: signed_url
