apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/backup-cm.yaml
  - manifests/backup-cronjob.yaml
images:
  - name: CUTLASS_BACKUP_IMAGE
    newName: europe-north1-docker.pkg.dev/my-project/cutlass-backup
    newTag: placeholder
