apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../service/manifests/cronjob.yaml
images:
  - name: CUTLASS_FDR_IMAGE
    newName: europe-north1-docker.pkg.dev/my-project/cutlass-feeder
    newTag: placeholder
