apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/ns.yaml
  - manifests/cm.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/stateful.yaml
  - db-init/database-init-sql.yaml
  - db-init/database-init-job.yaml
  - ../service/db/db-init-sql.yaml
  - ../service/db/db-init-job.yaml