apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/ns.yaml
  - manifests/cm.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/stateful.yaml
  - db-init/cutlass-db-init-sql.yaml
  - db-init/cutlass-db-init-job.yaml
  - db-init/table-structure-sql.yaml
  - db-init/table-structure-job.yaml
