name: Release application
on:
  push:
    paths:
      - cutlass-app/**
      - cutlass-backend/**
      - cutlass-feeder/**
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: ${{ secrets.REGISTRY }}
  REPOSITORY: cutlass-app
  IMAGE_APP: cutlass-app
  IMAGE_BCK: cutlass-backend
  IMAGE_FDR: cutlass-feeder
  SERVICE: cutlass-app-svc
  BRANCH: ${{ github.ref_name }}
  NAMESPACE: ${{ github.ref_name == 'master' && 'project' || github.ref_name }}
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      - name: 'Use gcloud CLI'
        run: gcloud info
      - name: 'Authorize login'
        run: gcloud --quiet auth configure-docker europe-north1-docker.pkg.dev
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Form the image names APP'
        run: echo "IMAGE_APP_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_APP:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: 'Form the image names BCK'
        run: echo "IMAGE_BCK_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_BCK:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: 'Form the image names FDR'
        run: echo "IMAGE_FDR_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE_FDR:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build --tag $IMAGE_APP_TAG ./cutlass-app        
          docker build --tag $IMAGE_BCK_TAG ./cutlass-backend   
          docker build --tag $IMAGE_FDR_TAG ./cutlass-feeder   

      - name: Publish APP
        run: docker push $IMAGE_APP_TAG

      - name: Publish BCK
        run: docker push $IMAGE_BCK_TAG

      - name: Publish FDR
        run: docker push $IMAGE_FDR_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      - name: Deploy
        run: |-
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE                   
          kubectl delete deployment --ignore-not-found=true cutlass-app 
          kustomize edit set image CUTLASS_APP_IMAGE=$IMAGE_APP_TAG \
            CUTLASS_BCK_IMAGE=$IMAGE_BCK_TAG \
            CUTLASS_FDR_IMAGE=$IMAGE_FDR_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout restart deployment 
          kubectl get services -n project -o wide